### PR TITLE
Fix %posttrans script execution (fixes #265)

### LINKED ISSUE #265: %posttrans scriptlets does not work, because of wrong invokation
Try to launch posttrans script like 

%posttrans
touch %{_sysconfdir}/posttrans-test-completed

And we get the following error messages in 

Jul 06 14:15:17 INOIP4903 packagekitd[3138]: Entering install phase
Jul 06 14:15:17 INOIP4903 packagekitd[3138]: Install progress update: 1 of 1
Jul 06 14:15:17 INOIP4903 kernel:  (0)[9050:sh]type=1800 audit(1594034117.578:279): pid=9050 uid=0 auid=4294967295 ses=4294967295 op="appraise_data" cause="missing-hash" comm="sh" name="/var/adm/update-scripts/posttransksJgTt/posttrans-test.rpmHDHnPd" dev="dm-0" ino=24705 res=0
Jul 06 14:15:17 INOIP4903 kernel:  (0)[9050:sh]type=1300 audit(1594034117.578:279): arch=40000028 syscall=11 per=800000 success=no exit=-13 a0=614a20 a1=614d00 a2=614a68 a3=d22b2500 items=1 ppid=3138 pid=9050 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="sh" exe="/bin/bash" key="x"
Jul 06 14:15:17 INOIP4903 kernel:  (0)[9050:sh]type=1307 audit(1594034117.578:279):  cwd="/"
Jul 06 14:15:17 INOIP4903 kernel:  (0)[9050:sh]type=1302 audit(1594034117.578:279): item=0 name="/var/adm/update-scripts/posttransksJgTt/posttrans-test.rpmHDHnPd" inode=24705 dev=fe:00 mode=0100700 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL
Jul 06 14:15:18 INOIP4903 PackageKit[3138]: install-files transaction /8_eaccceae from uid 0 finished with success after 2668ms

### PR DESCRIPTION
**Pull request by mlandres**
The scripts are execuable. No need to call them through 'sh -c'.

### CODE REVIEW

File: zypp/target/RpmPostTransCollector.cc [hunk 1]
```diff
@@ -127,7 +127,11 @@ namespace zypp
               npkgs++;
 
             MIL << "EXECUTE posttrans: " << script << " with argument: " << npkgs << endl;
-            ExternalProgram prog( (noRootScriptDir/script).asString() + " " +str::numstring( npkgs ), ExternalProgram::Stderr_To_Stdout, false, -1, true, _root );
+	    ExternalProgram::Arguments cmd;
+	    cmd.push_back( "/bin/sh" );
+	    cmd.push_back( (noRootScriptDir/script).asString() );
+	    cmd.push_back( str::numstring( npkgs ) );
+            ExternalProgram prog( cmd, ExternalProgram::Stderr_To_Stdout, false, -1, true, _root );
```
Comment (bzeller) [inline zypp/target/RpmPostTransCollector.cc:134]: Shouldn't we use initializer lists instead of push_back() if possible?

```suggestion
        ExternalProgram::Arguments cmd {
          "/bin/sh",
          (noRootScriptDir/script).asString(),
          str::numstring( npkgs )    
        };
        ExternalProgram prog( cmd, ExternalProgram::Stderr_To_Stdout, false, -1, true, _root );
```

**Review by bzeller — APPROVED** [review]

File: zypp/target/RpmPostTransCollector.cc (hunk 1 above)
Comment (mlandres) [reply zypp/target/RpmPostTransCollector.cc]: done
